name: Hitori Music n Media
favicon: null
layout_spectrum: 0.8208695887587965
typography_spectrum: 0.2753048955928534
title: Hitori Music n Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8681037412025034
  lightness: 0.9733238609042019
  saturation: 0.06100435554981232
  rhythmicContrast: 0.9063030434772372
purpose: []
