name: Hitori Music n Media
favicon: null
layout_spectrum: 1
typography_spectrum: 0.64547
title: Hitori Music n Media
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#3957c0'
    - '#19191a'
    - '#cbcbcb'
    - '#a2a2a2'
  brandStrength: 0.9375
  lightness: 0.125
  saturation: 0
  rhythmicContrast: 1
purpose: []
